### ISSUE TITLE
Unable to execute fHDHR with plugin enabled

### ISSUE THREAD

**Issue by bennydiamond** [fHDHR/fHDHR_plugin_origin_NextPVR#5]
```
[2022-01-17 03:53:01,007] NOOB - Loading  fHDHR v0.9.3-beta, fHDHR_web v0.9.2-beta

Checking and Installing Core Dependencies.

Traceback (most recent call last):

  File "/config/fHDHR/main.py", line 38, in <module>

    sys.exit(run.main(SCRIPT_DIR, fHDHR_web, deps))

  File "/config/fHDHR/fHDHR/cli/run.py", line 175, in main

    returned_code = start(args, script_dir, fHDHR_web, deps)

  File "/config/fHDHR/fHDHR/cli/run.py", line 134, in start

    return run(settings, logger, db, script_dir, fHDHR_web, plugins, versions, web, scheduler, deps)

  File "/config/fHDHR/fHDHR/cli/run.py", line 40, in run

    fhdhr = fHDHR_OBJ(settings, logger, db, plugins, versions, web, scheduler, deps)

  File "/config/fHDHR/fHDHR/__init__.py", line 48, in __init__

    self.fhdhr.origins = Origins(self.fhdhr)

  File "/config/fHDHR/fHDHR/origins/__init__.py", line 34, in __init__

    self.origin_selfadd()

  File "/config/fHDHR/fHDHR/origins/__init__.py", line 66, in origin_selfadd

    self.origins_dict[method] = self.fhdhr.plugins.plugins[plugin_name].Plugin_OBJ(plugin_utils)

  File "/config/fHDHR/plugins/fHDHR_plugin_origin_nextpvr/origin/__init__.py", line 14, in __init__

    self.login()

  File "/config/fHDHR/plugins/fHDHR_plugin_origin_nextpvr/origin/__init__.py", line 50, in login

    sid = self.get_sid()

  File "/config/fHDHR/plugins/fHDHR_plugin_origin_nextpvr/origin/__init__.py", line 61, in get_sid

    initiate_url = '%s/service?method=session.initiate&ver=1.0&device=fhdhr' % self.nextpvr_address

AttributeError: 'Plugin_OBJ' object has no attribute 'nextpvr_address'
```
Indeed `nextpvr_address` member doesn't look to be part of the object when get_sid() gets called.

config.ini has the following added in it

> [nextpvr]
> address = nextpvr
> port = 8866
> addrssless = false
> pin = 1234
> sid = none

nextpvr plugin freshly cloned from master

**Comment by deathbybandaid** [comment]
Please look at https://github.com/fHDHR/fHDHR_plugin_origin_NextPVR/pull/6

I haven't been using this specific plugin for a long time (I prefer tvheadend over nextpvr), but this would have been broken for a very long time!

Not even sure how `ssl=false` became `addrssless=false` in the readme, but the `nextpvr_address` property issue is totally my fault, so sorry about that.

give `main` branch another pull, and let me know if that works for you.

**Comment by bennydiamond** [comment]
Issue is resolved thank you.
Altough I might still stick to TVHeadend as well. Using NextPVR to handle tuners seems to introduce even more delay when selecting a channel in Plex!
